### ISSUE TITLE
Use full expansion of nested namespaces

### ISSUE THREAD

**Issue by sbellware** [eventide-project/log#1]
Remove `module Log::SomeModule` pattern. Replace with `module SomeModule` nested in `module Log`.

**Comment by sbellware** [comment]
@ntl It's been so long that I don't remember the context of this. Any ideas?

**Comment by ntl** [comment]
```ruby
module Foo::Bar::Baz
end
```

VS:

```ruby
module Foo
  module Bar
    module Baz
    end
  end
end
```

**Comment by sbellware** [comment]
Ah! Right. Got it.
