### ISSUE TITLE
Allow passing line callable in configure?

### ISSUE THREAD

**Issue by destructobeam** [eventide-project/log#7]
Would it be cool to add an override for the `Log::Format.line` method in `Log.configure`? Maybe ending up something like:

`Log::Format.line` becomes `Log::Format::Line.call`

```ruby
Log.configure(receiver, attr_name: nil, line_callable: Log::Format::Line)
```

Or would this be better handled by providing a telemetry sink to the logger?

Thanks!

**Comment by sbellware** [comment]
Hi, @destructobeam. This one fell through the cracks. Sorry for the late reply. It's been a busy time.

I'm not sure what the desired outcome is. Can you elaborate?

**Comment by destructobeam** [comment]
Oh lord, hard to remember exactly now. I think it was something around being able to format lines in to JSON or logfmt so that they were easily parseable by existing log collectors for centralised storage/analysis.

**Comment by sbellware** [comment]
Ah! Yeah, that's squarely outside the scope of this logger. We're not traditionally big fans of logging to application data formats and structured data formats. We're more in the Unix old school, and leveraging small tools that do small things. In this case, piping log output into some small tool that specialized the log lines for whatever particular tool is desired.

That said, there have been some hacks of this logger in the wild to make it work as a structured data logger that emits JSON in addition to the standard plain text log lines.

The logger will be written for Eventide's v3 generation. At that time, we're going to consider more elaborate use cases. At the same time, we must remain committed to simplicity, and avoiding elaborations - especially in the case of elements of the stack that are invoked most frequently.

**Comment by destructobeam** [comment]
Oh, I didn't mean mean all those use cases should be handled by this library, just that if you need to output in whatever format, you could write your own line format class and pass that in to the the loggers config method. It's a pretty minor change on this side.

Nicer to write a reusable class in ruby that you can share between services, than having to write some ops tool or awk/sed script that has to be deployed/maintained separately, and is not in the same codebase as the code requiring this lib.

**Comment by sbellware** [comment]
Yup. That design is probably we're we're going to take the logger in the next version. It's _somewhat_ possible now, but the current implementation is convoluted. We're not entirely enthusiastic about digging in deeper with it now. There's just a lot of stuff we need to remove and clarify before elaborating on it for new use cases. I'm not really sure that the user experience of specifying a formatter implementation when a logger is configured onto a receiver would be practicable at large. So, not sure we'd want to invest in such before giving it a good deal more consideration. And that is unlikely to get attention until the logger is re-written.

**Comment by destructobeam** [comment]
Okay, that’s cool. I can just fork in the meantime.

Was merely suggesting the above as a 5 minute, no API changes, solution.

**Comment by sbellware** [comment]
Well, it changes the configuration API. It would be ultimately availed to all users. And it's not ultimately how we would implement that feature unless it was an emergency change. It would also introduce complications for and require considerations for the `Log::Dependency` module. In the end, it would create special variation that would send the design in many conflicting directions at once, and directions that wouldn't really reflect a future implementation. The question isn't really how easy to add the feature, but how much inconsistency it introduces to the main thrust of the use of the library and its single responsibility, and how much difficulty it introduces when we change directions.
